#   ansible-playbook -vv main.yaml --extra-vars token=$(oc whoami -t)
#   ansible-playbook -vv main.yaml --tags 'build' --extra-vars token=$(oc whoami -t)
---
- hosts: localhost
  vars:
    ocp_project: samplepipeline
  tasks:
    - name: Locate oc client
      find:
        paths: "{{ ansible_env['PATH'].split(':') }}"
        patterns: 'oc'
      register: oc_cmd

    - set_fact:
        oc: "{{ oc_cmd.files[0]['path'] }}"
      when: oc_cmd.matched != 0

    - name: check openshift log in
      command: >-
        {{oc}} whoami
      ignore_errors: yes
      register: oc_whoami

    - name: load template
      command: >-
        {{oc}} apply -f https://raw.githubusercontent.com/openshift/origin/master/examples/jenkins/pipeline/samplepipeline.yaml -n openshift
      register: command_result
      failed_when: "command_result.rc != 0"
      
    - name: create openshift project "{{ocp_project}}"
      command: >-
        {{oc}} new-project {{ocp_project}} --display-name='Pipeline Sample' --description='Pipeline Sample'
      register: command_result
      failed_when: "command_result.rc != 0 and 'AlreadyExists' not in command_result.stderr"

    - name: create openshift application
      shell: "{{ oc }} new-app jenkins-pipeline-example"
      register: command_result
      failed_when: "command_result.rc != 0 and 'already exists' not in command_result.stderr"
      
    - name: start pipeline build
      shell: "{{ oc }} start-build sample-pipeline"
      register: command_result
