# dockerfile build demo example
#   ansible-playbook -vv main.yaml
# rebuild existing app from source only
#   ansible-playbook -vv main.yaml --tags 'build'
#
---
- hosts: localhost
  vars:
    project_dir: "./app"    
    ocp_user: developer
    ocp_pwd: developer
    ocp_server: 192.168.137.2:8443
    ocp_project: kompose
  tasks:
    - name: ensure app directory exists
      file: path={{project_dir}} state=directory

    - name: checkout git repo
      git:
        repo: git@github.com:eformat/kompose-examples.git
        dest: "{{project_dir}}"
        accept_hostkey: yes
      tags: build
    
    - name: check openshift log in
      shell: oc whoami
      ignore_errors: yes
      register: oc_whoami
      
    - name: login to openshift
      shell: "oc login -u {{ocp_user}} -p {{ocp_pwd}} --server=https://{{ocp_server}} --insecure-skip-tls-verify=true"
      tags: build
      when: ocp_user not in oc_whoami.stdout
      
    - name: create openshift project "{{ocp_project}}"
      shell: "oc new-project {{ocp_project}} --display-name='Kompose Demo' --description='Kompose Demo'"
      register: command_result
      failed_when: "command_result.rc != 0 and 'AlreadyExists' not in command_result.stderr"

    - name: add default project service acocunt to privileged scc
      shell: "oc adm policy add-scc-to-user privileged -z default -n {{ocp_project}} --as=system:admin"
      register: command_result
      failed_when: "command_result.rc != 0 and 'already exists' not in command_result.stderr"

    - name: convert docker compose to openshift
      shell: "kompose --file ./docker-compose.yaml --provider openshift up"
      args:
        chdir: "{{project_dir}}"

    - name: create openshift route
      shell: "oc expose svc frontend"
      register: command_result
      failed_when: "command_result.rc != 0 and 'AlreadyExists' not in command_result.stderr"      
        
