#   ansible-playbook -vv main.yaml --extra-vars token=$(oc whoami -t)
#   ansible-playbook -vv main.yaml --tags 'build' --extra-vars token=$(oc whoami -t)
---
- hosts: localhost
  vars:
    ocp_project: bluegreen
  tasks:
    - name: Locate oc client
      find:
        paths: "{{ ansible_env['PATH'].split(':') }}"
        patterns: 'oc'
      register: oc_cmd

    - set_fact:
        oc: "{{ oc_cmd.files[0]['path'] }}"
      when: oc_cmd.matched != 0

    - name: make blugreen route round-robin
      command: >-
        {{oc}} annotate route/bluegreen haproxy.router.openshift.io/balance=roundrobin
      register: command_result        

    - name: set backend service weights
      command: >-
        {{oc}} set route-backends routes/bluegreen blue=100 green=0
      register: command_result        

    - name: create ab pipeline
      command: >-
        {{oc}} create -f https://raw.githubusercontent.com/eformat/bluegreen/master/ab-pipeline.yaml
      register: command_result        
      
